
# load RSoXS stuff into the baseline

sd.baseline.extend([sam_viewer,
                    sam_X,
                    sam_Y,
                    sam_Z,
                    sam_Th,
                    BeamStopS,
                    BeamStopW,
                    Det_S,
                    Det_W,
                    Shutter_Y,
                    Izero_Y,
                    Izero_ds,
                    grating,
                    mirror2,
                    slits1,
                    slits2,
                    slits3,
                    en,
                    ring_current,
                    Beamstop_WAXS,
                    Beamstop_SAXS,
                    Izero_Diode,
                    Izero_Mesh,
                    Slit1_Top_I,
                    Slit1_IB_I,
                    DM4_PD,
                    mir1_pressure])
