## Devices are organized from upstream to downstream along SST1.
## Everything on this list other than 2D camera images are being archived.  TODO: make sure all new additions are archived.

[ring_current]
_target = "ophyd.EpicsSignalRO"
_group = "signals"
_role = "beam_current"
kind = "normal"
prefix = "SR:OPS-BI{DCCT:1}I:Real-I"
name = "NSLS-II Ring Current"

[Offset_C07U42_Horizontal] ## Want to remove the C07 portion from undulator name
_target = "ophyd.EpicsSignalRO"
_group = "signals"
kind = "normal"
prefix = "SR:C31-{AI}Aie7:Offset-x-Cal"
name = "Offset_C07U42_Horizontal"

[Offset_C07U42_Vertical]
_target = "ophyd.EpicsSignalRO"
_group = "signals"
kind = "normal"
prefix = "SR:C31-{AI}Aie7:Offset-y-Cal"
name = "Offset_C07U42_Vertical"

[Angle_C07U42_Horizontal] 
_target = "ophyd.EpicsSignalRO"
_group = "signals"
kind = "normal"
prefix = "SR:C31-{AI}Aie7:Angle-x-Cal"
name = "Angle_C07U42_Horizontal"

[Angle_C07U42_Vertical]
_target = "ophyd.EpicsSignalRO"
_group = "signals"
kind = "normal"
prefix = "SR:C31-{AI}Aie7:Angle-y-Cal"
name = "Angle_C07U42_Vertical"

[Gap_C07U42]
_target = "ophyd.EpicsSignalRO"
_group = "signals"
kind = "normal"
prefix = "SR:C07-ID:G1A{SST2:1-Ax:Gap}-Mtr.RBV"
name = "Gap_C07U42"

[Offset_EPU60_Horizontal]
_target = "ophyd.EpicsSignalRO"
_group = "signals"
kind = "normal"
prefix = "SR:C31-{AI}Aie7-2:Offset-x-Cal"
name = "Offset_EPU60_Horizontal"

[Offset_EPU60_Vertical]
_target = "ophyd.EpicsSignalRO"
_group = "signals"
kind = "normal"
prefix = "SR:C31-{AI}Aie7-2:Offset-y-Cal"
name = "Offset_EPU60_Vertical"

[Angle_EPU60_Horizontal]
_target = "ophyd.EpicsSignalRO"
_group = "signals"
kind = "normal"
prefix = "SR:C31-{AI}Aie7-2:Angle-x-Cal"
name = "Angle_EPU60_Horizontal"

[Angle_EPU60_Vertical]
_target = "ophyd.EpicsSignalRO"
_group = "signals"
kind = "normal"
prefix = "SR:C31-{AI}Aie7-2:Angle-y-Cal"
name = "Angle_EPU60_Vertical"

[Gap_EPU60]
_target = "ophyd.EpicsSignalRO"
_group = "signals"
kind = "normal"
prefix = "SR:C07-ID:G1A{SST1:1-Ax:Gap}-Mtr.RBV"
name = "Gap_EPU60"

[Phase_EPU60]
_target = "ophyd.EpicsSignalRO"
_group = "signals"
kind = "normal"
prefix = "SR:C07-ID:G1A{SST1:1-Ax:Phase}-Mtr.RBV"
name = "Phase_EPU60"

[Slits_EPU60_Frontend] ## TODO: This likely needs to get fixed/updated.  When I made this into a Slits object, I was not able to use functions like .wh().  I would get TypeError: unsupported operand type(s) for -: 'NoneType' and 'NoneType'
_target = "sst_base.slits.Slits"
_group = "slits"
prefix = "FE:C07A-OP{Slt:34-Ax:"
name = "EPU60 frontend slits"
kind = "hinted"
concurrent = 1
## TODO: After this is fixed, archive signal

[psh1]
_target = "sst_base.shutters.EPS_Shutter"
_group = "shutters"
openval = 0
closeval = 1
prefix = "XF:07ID-PPS{Sh:FE}"
name = "Front-End Shutter"
shutter_type = "FE"

[Temperature_L1]
_target = "ophyd.EpicsSignalRO"
_group = "signals"
kind = "normal"
prefix = "XF:07IDA-OP{Mir:L1}T:Msk-I"
name = "Temperature_L1"

[Temperature_M1]
_target = "ophyd.EpicsSignalRO"
_group = "signals"
kind = "normal"
prefix = "XF:07IDA-OP{Mir:1}T:Msk-I"
name = "Temperature_M1"

[mir1_pressure]
_target = "ophyd.EpicsSignalRO"
_group = "signals"
kind = "normal"
prefix = "XF:07IDA-VA:0{Mir:M1-CCG:1}P:Raw-I"
name = "Mirror 1 Vacuum Pressure"

[FS1_cam]
_target = "rsoxs.HW.cameras.StandardProsilicawstats" 
_group = "all_standard_pros" ## TODO: Does this need another group?
prefix = "XF:07ID-BI{BPM:1}"
name = "FS1 white beam stop Camera"
read_attrs = ['tiff','stats5']
## This is a rectangular mask through which both the soft and tender beams pass, and the frame can be used as a fluorescence screen.
## As a result, the rounded edge of the beam is visible on the frame, but it is cut off on the straight inner edge of the frame.  The camera is as far back as can be placed, so a larger portion of the beam cannot be seen.
## M1 reflects the beam through the mask/frame.

[FS6_cam]
_target = "rsoxs.HW.cameras.StandardProsilicawstats" 
_group = "all_standard_pros" ## TODO: Does this need another group?
prefix = "XF:07ID-BI{BPM:6}"
name = "FS6 Camera"
read_attrs = ['tiff','stats5']

[psh4]
_target = "sst_base.shutters.EPS_Shutter"
_group = "shutters"
shutter_type = "PH"
openval = 0
closeval = 1
prefix = "XF:07IDA-PPS{PSh:4}"
name = "Hutch Photon Shutter"

## GV14

## M2 and PGM
## RSoXS 250 l/mm grating is made from nickel oxide.  250 l/mm is made from gold.  1200 l/mm grating is made from gold.
[Temperature_MonoPGM]
_target = "ophyd.EpicsSignalRO"
_group = "signals"
kind = "normal"
prefix = "XF:07IDA-OP{Mono:PGM}T:Grg-I"
name = "Temperature_MonoPGM"

## GV15

## M3
[Temperature_M3]
_target = "ophyd.EpicsSignalRO"
_group = "signals"
kind = "normal"
prefix = "XF:07IDA-OP{Mir:2}T:Mir-I"
name = "Temperature_M3"

[FS7_cam]
_target = "rsoxs.HW.cameras.StandardProsilicawstats"
_group = "all_standard_pros" ## TODO: Does this need another group?
prefix = "XF:07ID-BI{BPM:7}"
name = "FS7 pink beam stop Camera"
read_attrs = ['tiff','stats5']

[psh10]
_target = "sst_base.shutters.EPS_Shutter"
_group = "shutters"
shutter_type = "PH"
openval = 0
closeval = 1
prefix = "XF:07IDA-PPS{PSh:10}"
name = "Photon Shutter 10"

## GV26

## DM6 and FS12

## Precision slit C

## GV27

[sst_control]
_target = "ophyd.EpicsSignalRO"
_group = "signals"
kind = "normal"
prefix = "XF:07ID1-CT{Bl-Ctrl}Endstn-Sel"
name = "SST endstation in Control"
string = True

[Slit1_Current_Bottom]
_target = "ophyd.EpicsSignalRO"
_group = "signals"
kind = "normal"
prefix = "XF:07ID-ES1{Slt1:I400-1}:IC1_MON"
name = "RSoXS Slit 1 Bottom Current"

[Slit1_Current_Top]
_target = "ophyd.EpicsSignalRO"
_group = "signals"
kind = "normal"
prefix = "XF:07ID-ES1{Slt1:I400-1}:IC2_MON"
name = "RSoXS Slit 1 Top Current"

[Slit1_Current_Inboard]
_target = "ophyd.EpicsSignalRO"
_group = "signals"
kind = "normal"
prefix = "XF:07ID-ES1{Slt1:I400-1}:IC3_MON"
name = "RSoXS Slit 1 In Board Current"

[Slit1_Current_Outboard]
_target = "ophyd.EpicsSignalRO"
_group = "signals"
kind = "normal"
prefix = "XF:07ID-ES1{Slt1:I400-1}:IC4_MON"
name = "RSoXS Slit 1 Out Board Current"

[Slit1_i400_cap]
_target = "ophyd.EpicsSignal"
_group = "signals"
kind = "normal"
prefix = "XF:07ID-ES1{Slt1:I400-1}:CAP_SP"
name = "RSoXS Slit 1 i400 capasitor"
string = True

[Slit1_i400_enable]
_target = "ophyd.EpicsSignal"
_group = "signals"
kind = "normal"
prefix = "XF:07ID-ES1{Slt1:I400-1}:ENABLE_IC_UPDATES"
name = "RSoXS Slit 1 i400 enable"
string = True

[Slit1_i400_npnts]
_target = "ophyd.EpicsSignal"
_group = "signals"
kind = "normal"
prefix = "XF:07ID-ES1{Slt1:I400-1}:TRIGPOINTS_SP"
name = "RSoXS Slit 1 i400 trigger points"
string = True

[Slit1_i400_read_time]
_target = "ophyd.EpicsSignal"
_group = "signals"
kind = "normal"
prefix = "XF:07ID-ES1{Slt1:I400-1}:PERIOD_SP"
name = "RSoXS Slit 1 i400  read time"
string = True

[Slit1_i400_mode]
_target = "ophyd.EpicsSignal"
_group = "signals"
kind = "normal"
prefix = "XF:07ID-ES1{Slt1:I400-1}:IC_UPDATE_MODE"
name = "RSoXS Slit 1 i400 mode"
string = True

[Slit1_i400_accum]
_target = "ophyd.EpicsSignal"
_group = "signals"
kind = "normal"
prefix = "XF:07ID-ES1{Slt1:I400-1}:ACCUM_SP"
name = "RSoXS Slit 1 i400 mode"
string = True

[Izero_Mesh]
_target = "ophyd.EpicsSignalRO"
_group = "signals"
kind = "normal"
prefix = "XF:07ID-ES1{Slt1:I400-1}:IC1_MON"
name = "RSoXS Au Mesh Current"

[Izero_Diode] ## This is Jamie's definition, can be used for flyscanning (?)
_target = "ophyd.EpicsSignalRO"
_group = "signals"
kind = "normal"
prefix = "XF:07ID-ES1{DMR:I400-1}:IC3_MON"
name = "Izero Photodiode"

[Izero_cam]
_target = "rsoxs.HW.cameras.StandardProsilicawstats"
_group = "all_standard_pros"
prefix = "XF:07ID1-ES:1{Scr:1}"
name = "Izero YAG Camera"
read_attrs=['tiff','stats5']

[Izero_Y]
_target = "sst_base.motors.PrettyMotorFMBODeadband"
_group = "motors"
prefix = "XF:07ID2-ES1{Scr-Ax:1}Mtr"
name = "Izero Assembly Vertical Translation" ## TODO: would like to name it something more generic like RSoXS diagnostic module to indicate that there is also a yag and photodiode
kind = "hinted"

[Izero_update_time] ## No longer relevant because quadEM is broken
_target = "ophyd.EpicsSignal"
_group = "signals"
kind = "normal"
prefix = "XF:07ID1-BI{EM:1}EM180:AveragingTime"
name = "RSoXS quadem Averaging Time"

## RSoXS slit 2

[Shutter_Y]
_target = "sst_base.motors.PrettyMotorFMBODeadband"
_group = "motors"
prefix = "XF:07ID2-ES1{FSh-Ax:1}Mtr"
name = "Shutter Vertical Translation" ## Fast shutter
kind = "hinted"

## GV27A

## RSoXS slit 3

[Sample_TEY]
_target = "ophyd.EpicsSignalRO"
_group = "signals"
kind = "normal"
prefix = "XF:07ID-ES1{Slt1:I400-1}:IC2_MON"
name = "RSoXS Sample Current"

[Sample_cam]
_target = "sst_base.cameras.StandardProsilica"
_group = "all_standard_pros"
prefix = "XF:07ID1-ES:1{Scr:4}"
name = "RSoXS Sample Area Camera" ## TODO: Would like to rename to "RSoXS Sample optical area camera, front view"

[Side_cam]
_target = "sst_base.cameras.StandardProsilica"
_group = "all_standard_pros"
prefix = "XF:07ID1-ES:1{Scr:2}"
name = "RSoXS Sample Area Camera" ## TODO: Would like to rename to "RSoXS Sample optical area camera, side view"

[sam_viewer]
_target = "sst_base.motors.PrettyMotorFMBO"
_group = "motors"
prefix = "XF:07ID2-ES1{ImgY-Ax:1}Mtr"
name = "RSoXS Sample Imager"
kind = "hinted"

[SampleViewer_cam]
_target = "sst_base.cameras.ColorProsilicaWithTIFFV33"
_group = "all_standard_pros"
prefix = "XF:07ID1-ES:1{Scr:5}"
name = "Sample Imager Detector Area Camera" ## TODO: Would like to rename to "Solid sample bar imager detector area camera"
read_attrs = ["tiff"]

[sam_X]
_target = "sst_base.motors.PrettyMotorFMBODeadbandFlyer"
_group = "motors"
kind = "hinted"
name = "RSoXS Sample Outboard-Inboard"
prefix = "XF:07ID2-ES1{Stg-Ax:X}Mtr"

[sam_Y]
_target = "sst_base.motors.PrettyMotorFMBODeadbandFlyer"
_group = "motors"
kind = "hinted"
name = "RSoXS Sample Up-Down"
prefix = "XF:07ID2-ES1{Stg-Ax:Y}Mtr"

[sam_Z]
_target = "sst_base.motors.PrettyMotorFMBODeadbandFlyer"
_group = "motors"
kind = "hinted"
name = "RSoXS Sample Downstream-Upstream"
prefix = "XF:07ID2-ES1{Stg-Ax:Z}Mtr"

[sam_Th]
_target = "sst_base.motors.PrettyMotorFMBODeadband"
_group = "motors"
kind = "hinted"
name = "RSoXS Sample Rotation"
prefix = "XF:07ID2-ES1{Stg-Ax:Yaw}Mtr"

[TEMX]
_target = "sst_base.motors.PrettyMotor"
_group = "motors"
kind = "hinted"
name = "RSoXS TEM Upstream-Downstream"  ## TODO: I would like to update the variable names so that they are consistent with NSLS II coordinates, in which x is inboard-outboard and z is upstream-downstream.
prefix = "XF:07ID1-ES:1{Smpl-Ax:X}Mtr"

[TEMY]
_target = "sst_base.motors.PrettyMotor"
_group = "motors"
kind = "hinted"
name = "RSoXS TEM Up-Down"
prefix = "XF:07ID1-ES:1{Smpl-Ax:Y}Mtr"

[TEMZ]
_target = "sst_base.motors.PrettyMotor"
_group = "motors"
kind = "hinted"
name = "RSoXS TEM Inboard-Outboard"
prefix = "XF:07ID1-ES:1{Smpl-Ax:Z}Mtr"

[tem_tempstage]
_target = "rsoxs.HW.lakeshore.Lakeshore336Picky" 
_group = "sample_environments" ## TODO: I made a new group, feel free to rename.
kind = "normal"
name = "TEM temperature controller"
prefix = "XF:07ID2-ES1{TCtrl:1}LS336:TC1:"

[BeamStopW] ## TODO: rename so that it is more obvious which is a signal vs. a motor
_target = "sst_base.motors.PrettyMotorFMBODeadband"
_group = "motors"
kind = "hinted"
name = "Beam Stop WAXS"
prefix = "XF:07ID2-ES1{BS-Ax:1}Mtr"

[Beamstop_WAXS] ## This is Jamie's definition, can be used for flyscanning (?)
_target = "ophyd.EpicsSignalRO"
_group = "signals"
kind = "normal"
prefix = "XF:07ID-ES1{DMR:I400-1}:IC1_MON"
name = "WAXS Beamstop"

[diode_i400_cap]
_target = "ophyd.EpicsSignal"
_group = "signals"
kind = "normal"
prefix = "XF:07ID-ES1{DMR:I400-1}:CAP_SP"
name = "RSoXS diode i400 capasitor"
string = True

[diode_i400_enable]
_target = "ophyd.EpicsSignal"
_group = "signals"
kind = "normal"
prefix = "XF:07ID-ES1{DMR:I400-1}:TRIGPOINTS_SP"
name = "RSoXS diode i400 trigger points"
string = True

[diode_i400_npnts]
_target = "ophyd.EpicsSignal"
_group = "signals"
kind = "normal"
prefix = "XF:07ID-ES1{DMR:I400-1}:ENABLE_IC_UPDATES"
name = "RSoXS diode i400 enable"
string = True

[diode_i400_mode]
_target = "ophyd.EpicsSignal"
_group = "signals"
kind = "normal"
prefix = "XF:07ID-ES1{DMR:I400-1}:IC_UPDATE_MODE"
name = "RSoXS diode i400 mode"
string = True

[diode_i400_accum]
_target = "ophyd.EpicsSignal"
_group = "signals"
kind = "normal"
prefix = "XF:07ID-ES1{DMR:I400-1}:ACCUM_SP"
name = "RSoXS diode i400  accumulation mode"
string = True

[diode_i400_read_time]
_target = "ophyd.EpicsSignal"
_group = "signals"
kind = "normal"
prefix = "XF:07ID-ES1{DMR:I400-1}:PERIOD_SP"
name = "RSoXS diode i400 read time"
string = True

[diode_i400_PDU]
_target = "ophyd.EpicsSignal"
_group = "signals"
kind = "normal"
prefix = "XF:07ID-CT{RG:C1-PDU:1}Sw:8-Sel"
name = "RSoXS diode power control"
string = True

[DiodeRange]
_target = "ophyd.EpicsSignal"
_group = "signals"
prefix = "XF:07ID-ES1{DMR:I400-1}:RANGE_BP"

[Det_W]
_target = "sst_base.motors.PrettyMotorFMBODeadband"
_group = "motors"
kind = "hinted"
name = "Detector WAXS Translation"
prefix = "XF:07ID2-ES1{Det-Ax:2}Mtr"

[waxs_det]
_target = "rsoxs.Base.detectors.RSOXSGreatEyesDetector" 
_group = "all_standard_pros" ## TODO: Not sure if this belongs elsewhere.
prefix = "XF:07ID1-ES:1{GE:2}"
name = "Wide Angle CCD Detector" ## TODO: Not sure how this is different from DetS_cam
read_attrs = ['tiff', 'stats1.total', 'saturated','under_exposed','cam']

[BeamStopS]
_target = "sst_base.motors.PrettyMotorFMBODeadband"
_group = "motors"
kind = "hinted"
name = "Beam Stop SAXS"
prefix = "XF:07ID2-ES1{BS-Ax:2}Mtr"

[Beamstop_SAXS] ## This is Jamie's definition, can be used for flyscanning (?)
_target = "ophyd.EpicsSignalRO"
_group = "signals"
kind = "normal"
prefix = "XF:07ID-ES1{DMR:I400-1}:IC2_MON"
name = "SAXS Beamstop"

[Det_S]
_target = "sst_base.motors.PrettyMotorFMBODeadband"
_group = "motors"
kind = "hinted"
name = "Detector SAXS Translation"
prefix = "XF:07ID2-ES1{Det-Ax:1}Mtr"

[DetS_cam]
_target = "sst_base.cameras.StandardProsilica"
_group = "all_standard_pros"
prefix = "XF:07ID1-ES:1{Scr:3}"
name = "WAXS Detector Area Camera"

[mc19_fault]
_target = "ophyd.EpicsSignalRO"
_group = "signals"
prefix = "SST1_Upstream:MC19AmpFaultSum-Sts"
name = "MC19 Amp Fault"

[mc20_fault]
_target = "ophyd.EpicsSignalRO"
_group = "signals"
prefix = "SST1_Upstream:MC20AmpFaultSum-Sts"
name = "MC20 Amp Fault"

[mc21_fault]
_target = "ophyd.EpicsSignalRO"
_group = "signals"
prefix = "SST1_Upstream:MC21AmpFaultSum-Sts"
name = "MC21 Amp Fault"

## GV28

[psh7]
_target = "sst_base.shutters.EPS_Shutter"
_group = "shutters"
_role = "default_shutter"
shutter_type = "PH"
openval = 0
closeval = 1
prefix = "XF:07IDA-PPS{PSh:7}"
name = "Photon Shutter 7"

## M4C/M4D

[DownstreamLargeDiode] 
_target = "ophyd.EpicsSignalRO"
_group = "signals"
kind = "normal"
prefix = "XF:07ID-ES1{DMR:I400-1}:IC4_MON"
name = "DownstreamLargeDiode"

[bpm13_sum]
_target = "ophyd.EpicsSignalRO"
_group = "signals"
prefix = "XF:07ID-BI{BPM:13}Stats5:Total_RBV"
name = "Downstream Izero Phosphor Intensity"

[Izero_ds]
_target = "sst_base.motors.PrettyMotorFMBO"
_group = "motors"
prefix = "XF:07ID2-BI{Diag:07-Ax:Y}Mtr"
name = "Downstream Izero DM7 Vertical Translation" ## TODO: would like to name it something more generic like diagnostic module 7 to indicate that there is also a yag and photodiode.  In the description, I can indicate that it is downstream of RSoXS.
kind = "hinted"

[dm7] ## TODO: I believe this is a repeat of the above Izero_ds, but the motor class and normal vs. hinting is different, so I am not sure which one is more correct
_target = "sst_base.motors.PrettyMotorFMBODeadbandFlyer"
_group = "motors"
prefix = "XF:07ID2-BI{Diag:07-Ax:Y}Mtr"
name = "Downstream diagnostic module translation" 
kind = "normal"

## GV29

## LARIAT 1

[psh8]
_target = "sst_base.shutters.EPS_Shutter"
_group = "shutters"
shutter_type = "PH"
openval = 0
closeval = 1
prefix = "XF:07IDA-PPS{PSh:8}"
name = "Photon Shutter 8"

## GV30

## M5C

## FS14

## GV31

## PEY NEXAFS

## PSH9

## GV32

## FS15

## GV33

## LARIAT 2


## TODO: I would like to rename some of the devices, but I will do so after those definitions have been successfully removed from the rsoxs repository
